project:
  type: website

website:
  title: "Camden Kay"
  navbar:
    right:
      - text: Home
        href: https://camdenk.github.io
      - about.qmd
      - resume.qmd
      - text: mlbplotR
        href: https://camdenk.github.io/mlbplotR
      - icon: github
        href: https://github.com/camdenk
      - icon: twitter
        href: https://twitter.com/k_camden
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    
execute:
  freeze: auto

editor: visual

